export const IPC_CHANNELS = {
  PROJECT_OWNERS_LIST: 'project-owners:list',
  PROJECT_OWNERS_GET_BY_ID: 'project-owners:get-by-id',
  PROJECT_OWNERS_CREATE: 'project-owners:create',
  PROJECT_OWNERS_UPDATE: 'project-owners:update',
  PROJECT_OWNERS_DELETE: 'project-owners:delete',
  PROJECT_OWNERS_COUNT: 'project-owners:count',

  BROKERS_LIST: 'brokers:list',
  BROKERS_GET_BY_ID: 'brokers:get-by-id',
  BROKERS_CREATE: 'brokers:create',
  BROKERS_UPDATE: 'brokers:update',
  BROKERS_DELETE: 'brokers:delete',
  BROKERS_COUNT: 'brokers:count',

  ROUTES_LIST: 'routes:list',
  ROUTES_LIST_WITH_COUNTS: 'routes:list-with-counts',
  ROUTES_RENAME: 'routes:rename',

  PRODUCTS_LIST: 'products:list',
  PRODUCTS_SEARCH: 'products:search',
  PRODUCTS_GET_BY_ID: 'products:get-by-id',
  PRODUCTS_CREATE: 'products:create',
  PRODUCTS_UPDATE: 'products:update',
  PRODUCTS_DELETE: 'products:delete',
  PRODUCTS_COUNT: 'products:count',
  PRODUCTS_IMPORT_CSV: 'products:import-csv',
  DIALOG_OPEN_CSV: 'dialog:open-csv',

  CUSTOMERS_LIST: 'customers:list',
  CUSTOMERS_LIST_BY_ROUTE: 'customers:list-by-route',
  CUSTOMERS_GET_BY_ID: 'customers:get-by-id',
  CUSTOMERS_SEARCH: 'customers:search',
  CUSTOMERS_CREATE: 'customers:create',
  CUSTOMERS_UPDATE: 'customers:update',
  CUSTOMERS_DELETE: 'customers:delete',
  CUSTOMERS_COUNT: 'customers:count',
  CUSTOMERS_IMPORT_EXCEL: 'customers:import-excel',
  DIALOG_OPEN_EXCEL: 'dialog:open-excel',

  INVOICES_LIST: 'invoices:list',
  INVOICES_GET_BY_ID: 'invoices:get-by-id',
  INVOICES_GET_WITH_DETAILS: 'invoices:get-with-details',
  INVOICES_LIST_BY_CUSTOMER: 'invoices:list-by-customer',
  INVOICES_CREATE: 'invoices:create',
  INVOICES_BUILD_LOAD_FORM: 'invoices:build-load-form',
  INVOICES_DELETE: 'invoices:delete',
  INVOICES_CANCEL: 'invoices:cancel',
  INVOICES_PAY: 'invoices:pay',
  INVOICES_COUNT: 'invoices:count',

  CUSTOMERS_PAY: 'customers:pay',

  PAYMENTS_LIST_BY_INVOICE: 'payments:list-by-invoice',
  PAYMENTS_LIST_BY_CUSTOMER: 'payments:list-by-customer',
  PAYMENTS_LIST_RECENT: 'payments:list-recent',
  PAYMENTS_REMOVE: 'payments:remove',

  STOCK_LIST: 'stock:list',
  STOCK_LIST_BY_PRODUCT: 'stock:list-by-product',
  STOCK_RESTOCK: 'stock:restock',
  STOCK_ADJUST: 'stock:adjust',
  STOCK_LEVELS: 'stock:levels',

  DASHBOARD_SUMMARY: 'dashboard:summary',

  EXPENSES_LIST_BY_DATE: 'expenses:list-by-date',
  EXPENSES_DAY_SUMMARY: 'expenses:day-summary',
  EXPENSES_RANGE_SUMMARY: 'expenses:range-summary',
  EXPENSES_SAVE: 'expenses:save',
  EXPENSES_DELETE: 'expenses:delete',

  DIALOG_SAVE_BACKUP: 'dialog:save-backup',
  DIALOG_OPEN_BACKUP: 'dialog:open-backup',
  BACKUP_CREATE: 'backup:create',
  BACKUP_VALIDATE: 'backup:validate',
  BACKUP_RESTORE: 'backup:restore',

  SETTINGS_LIST: 'settings:list',
  SETTINGS_GET: 'settings:get',
  SETTINGS_GET_VALUE: 'settings:get-value',
  SETTINGS_SET: 'settings:set',
  SETTINGS_UPDATE: 'settings:update',
  SETTINGS_BULK_UPDATE: 'settings:bulk-update',
  SETTINGS_DELETE: 'settings:delete',

  HISTORY_LIST: 'history:list',
  HISTORY_RECENT: 'history:recent',
} as const

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS]