export const IPC_CHANNELS = {
  PRODUCTS_LIST: 'products:list',
  PRODUCTS_LIST_WITH_STOCK: 'products:list-with-stock',
  PRODUCTS_GET_BY_ID: 'products:get-by-id',
  PRODUCTS_GET_BY_SKU: 'products:get-by-sku',
  PRODUCTS_SEARCH: 'products:search',
  PRODUCTS_SEARCH_WITH_STOCK: 'products:search-with-stock',
  PRODUCTS_CREATE: 'products:create',
  PRODUCTS_UPDATE: 'products:update',
  PRODUCTS_DELETE: 'products:delete',
  PRODUCTS_ADD_STOCK: 'products:add-stock',
  PRODUCTS_COUNT: 'products:count',

  INVENTORY_LIST_MOVEMENTS: 'inventory:list-movements',
  INVENTORY_LIST_MOVEMENTS_WITH_CONTEXT: 'inventory:list-movements-with-context',
  INVENTORY_GET_BY_ID: 'inventory:get-by-id',
  INVENTORY_CURRENT_QUANTITY: 'inventory:current-quantity',
  INVENTORY_CURRENT_QUANTITIES: 'inventory:current-quantities',
  INVENTORY_STOCK_SUMMARY: 'inventory:stock-summary',
  INVENTORY_STOCK_SUMMARIES: 'inventory:stock-summaries',
  INVENTORY_OUT_OF_STOCK: 'inventory:out-of-stock',
  INVENTORY_SET_OPENING_STOCK: 'inventory:set-opening-stock',

  CUSTOMERS_LIST: 'customers:list',
  CUSTOMERS_LIST_WITH_BALANCE: 'customers:list-with-balance',
  CUSTOMERS_GET_BY_ID: 'customers:get-by-id',
  CUSTOMERS_GET_WITH_BALANCE: 'customers:get-with-balance',
  CUSTOMERS_SEARCH: 'customers:search',
  CUSTOMERS_CREATE: 'customers:create',
  CUSTOMERS_UPDATE: 'customers:update',
  CUSTOMERS_DELETE: 'customers:delete',
  CUSTOMERS_COUNT: 'customers:count',

  CUSTOMER_LEDGER_LIST_BY_CUSTOMER: 'customer-ledger:list-by-customer',
  CUSTOMER_LEDGER_LIST: 'customer-ledger:list',
  CUSTOMER_LEDGER_LATEST: 'customer-ledger:latest',
  CUSTOMER_LEDGER_GET_BY_ID: 'customer-ledger:get-by-id',
  CUSTOMER_LEDGER_GET_BALANCE: 'customer-ledger:get-balance',
  CUSTOMER_LEDGER_GET_OUTSTANDING: 'customer-ledger:get-outstanding',
  CUSTOMER_LEDGER_BALANCE_AT_DATE: 'customer-ledger:balance-at-date',
  CUSTOMER_LEDGER_SUMMARY: 'customer-ledger:summary',
  CUSTOMER_LEDGER_CREATE: 'customer-ledger:create',

  PAYMENTS_LIST: 'payments:list',
  PAYMENTS_GET_BY_ID: 'payments:get-by-id',
  PAYMENTS_LIST_BY_CUSTOMER: 'payments:list-by-customer',
  PAYMENTS_CREATE: 'payments:create',
  PAYMENTS_DELETE: 'payments:delete',

  INVOICES_LIST: 'invoices:list',
  INVOICES_GET_BY_ID: 'invoices:get-by-id',
  INVOICES_GET_ITEMS: 'invoices:get-items',
  INVOICES_LIST_BY_CUSTOMER: 'invoices:list-by-customer',
  INVOICES_LIST_BY_STATUS: 'invoices:list-by-status',
  INVOICES_CREATE: 'invoices:create',
  INVOICES_UPDATE: 'invoices:update',
  INVOICES_CANCEL: 'invoices:cancel',
  INVOICES_DELETE: 'invoices:delete',

  RESTOCKS_LIST: 'restocks:list',
  RESTOCKS_GET_BY_ID: 'restocks:get-by-id',
  RESTOCKS_GET_ITEMS: 'restocks:get-items',
  RESTOCKS_LIST_BY_STATUS: 'restocks:list-by-status',
  RESTOCKS_CREATE: 'restocks:create',
  RESTOCKS_UPDATE: 'restocks:update',
  RESTOCKS_MARK_RECEIVED: 'restocks:mark-received',
  RESTOCKS_CANCEL: 'restocks:cancel',
  RESTOCKS_DELETE: 'restocks:delete',

  BUSINESS_PROFILE_GET: 'business-profile:get',
  BUSINESS_PROFILE_UPDATE: 'business-profile:update',

  SETTINGS_LIST: 'settings:list',
  SETTINGS_GET: 'settings:get',
  SETTINGS_GET_VALUE: 'settings:get-value',
  SETTINGS_SET: 'settings:set',
  SETTINGS_UPDATE: 'settings:update',
  SETTINGS_BULK_UPDATE: 'settings:bulk-update',
  SETTINGS_DELETE: 'settings:delete',

  REPORTS_SALES: 'reports:sales',
  REPORTS_INVENTORY: 'reports:inventory',
  REPORTS_CUSTOMERS: 'reports:customers',
  REPORTS_PROFIT_LOSS: 'reports:profit-loss',

  STOCK_ADJUSTMENTS_LIST: 'stock-adjustments:list',
  STOCK_ADJUSTMENTS_GET_BY_ID: 'stock-adjustments:get-by-id',
  STOCK_ADJUSTMENTS_LIST_BY_PRODUCT: 'stock-adjustments:list-by-product',
  STOCK_ADJUSTMENTS_CREATE: 'stock-adjustments:create',
  STOCK_ADJUSTMENTS_DELETE: 'stock-adjustments:delete',

  PAYMENTS_LIST_BY_INVOICE: 'payments:list-by-invoice',
  PAYMENTS_LIST_BETWEEN: 'payments:list-between',

  INVOICES_GET_WITH_ITEMS: 'invoices:get-with-items',
  INVOICES_LIST_BETWEEN: 'invoices:list-between',
  INVOICES_REFRESH_OVERDUE: 'invoices:refresh-overdue',

  RESTOCKS_GET_WITH_ITEMS: 'restocks:get-with-items',
  RESTOCKS_LIST_WITH_COUNTS: 'restocks:list-with-counts',

  REPORTS_PAYMENTS: 'reports:payments',
  REPORTS_RESTOCKS: 'reports:restocks',
  REPORTS_STOCK_MOVEMENTS: 'reports:stock-movements',

  DASHBOARD_OVERVIEW: 'dashboard:overview',

  BACKUP_CREATE: 'backup:create',
  BACKUP_VALIDATE: 'backup:validate',
  BACKUP_RESTORE: 'backup:restore',

  DIALOG_SELECT_FILE: 'dialog:select-file',
  DIALOG_SELECT_DIRECTORY: 'dialog:select-directory',
  DIALOG_SAVE_FILE: 'dialog:save-file',
} as const

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS]
